name: CI Pipeline

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          pip install --upgrade pip pylint
          pip install .[dev]
      - name: check black formating
        run: |
          black --check --diff --config ./pyproject.toml .
      - name: lint changed and added files
        run: |
          pylint --rcfile=.pylintrc --fail-under 9.5 shiny_invoice/
